name = "p5js-sketches"
type = "javascript"

account_id = ""
route = ""
workers_dev = true
zone_id = ""

compatibility_date = "2021-12-17"

kv_namespaces = [
  {binding = "KV", id = "d470f8fef2fb416da2389da06100e9ea"},
]

[site]
bucket = "./public"
entry-point = "."

[build]
command = "npm run build:worker"
watch_dir = "build/index.js"

[build.upload]
format = "service-worker"
